/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author swallak
 */
public class SignIn extends javax.swing.JPanel {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomLabel = new javax.swing.JLabel();
        pseudoLabel = new javax.swing.JLabel();
        pseudoTextField = new javax.swing.JTextField();
        signIn = new javax.swing.JButton();
        birthdayLabel = new javax.swing.JLabel();
        birthdayTextField = new javax.swing.JTextField();

        roomLabel.setText("Room");

        pseudoLabel.setText("Pseudo");

        pseudoTextField.setText("your pseudo");
        pseudoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pseudoTextFieldMouseClicked(evt);
            }
        });

        signIn.setText("SignIn");

        birthdayLabel.setText("Birthday");

        birthdayTextField.setText("DD/MM/YYYY");
        birthdayTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birthdayTextFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(birthdayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthdayTextField))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(roomLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pseudoLabel)
                            .addGap(18, 18, 18)
                            .addComponent(pseudoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(signIn)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomLabel)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pseudoLabel)
                    .addComponent(pseudoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayLabel)
                    .addComponent(birthdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(signIn)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        roomLabel.getAccessibleContext().setAccessibleName("Room");
    }// </editor-fold>//GEN-END:initComponents

    private void pseudoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pseudoTextFieldMouseClicked
    
        pseudoTextField.setText("");
    //roomLabel.repaint();// TODO add your handling code here:
    }//GEN-LAST:event_pseudoTextFieldMouseClicked

    private void birthdayTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthdayTextFieldMouseClicked
    
        birthdayTextField.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_birthdayTextFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField birthdayTextField;
    private javax.swing.JLabel pseudoLabel;
    private javax.swing.JTextField pseudoTextField;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JButton signIn;
    // End of variables declaration//GEN-END:variables
}
